name: Filter Pull Request Events

on:
    pull_request:
        types:
            - opened
            - closed

jobs:
    filter-events:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Print Event Info
              run: echo "Pull request event triggered on the main branch."