name: Filter Pull Request Events

on:
    workflow_dispatch:

    push:
        branches:
            - main
            - '!feature/*'
    pull_request:
        types:
            - opened
            - closed
        paths-ignore:
            - 'docs/**'
            - 'README.md'
        branches:
            - main

jobs:
    filter-events:
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Print Event Info
              run: echo "Pull request event triggered on the main branch."